# Generated by Django 3.2 on 2022-01-25 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='choice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
