# Generated by Django 3.2 on 2022-01-25 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0002_auto_20220125_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
